### PR TITLE
Use .bc extension for LLVM bitcode, some docs

### PR DESCRIPTION
**Pull request by brenhinkeller**
Just to clarify what's in the file and avoid conflict with a potential extension-less executable if it becomes feasible to make those

### CODE REVIEW

**Comment by brenhinkeller** [comment]
Added a few docstrings too, and a possible fix for the can't-see-other-compiler-errors issue

**Comment by MasonProtter** [comment]
Thanks! I think if we're gonna do this we can just remove the `try/catch` entirely.

**Comment by brenhinkeller** [comment]
Found one more weird thing -- apparently the compiler actually cares about the name of the llvm bitcode and doesn't like the `bc` suffix I added

**Comment by MasonProtter** [comment]
Yeah, I think it should actually be called `.o`.

**Comment by brenhinkeller** [comment]
Oh!

**Comment by brenhinkeller** [comment]
That runs without error so you must be right

**Comment by brenhinkeller** [comment]
For some reason I thought that was for something else

**Comment by MasonProtter** [comment]
I didn't realize it mattered, so I just changed it to that.

**Comment by brenhinkeller** [comment]
Yeah, I had no idea so i hadn't even tested (F) -- but easy enough fix I guess!

**Pull request merged**
